# Generated by Django 5.1.4 on 2025-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseprogress_current_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='completed_blocks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='current_section',
            field=models.IntegerField(default=0),
        ),
    ]
