# Generated by Django 5.1.4 on 2025-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprogress_completed_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_tests',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='exp_earned',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='stars_earned',
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_blocks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
