# Generated by Django 5.1.4 on 2025-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
