# Generated by Django 5.1.4 on 2026-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_userprofile_birth_date_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_math',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest_programming',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_difficulties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motivation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_learning_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_learning_time',
            field=models.CharField(blank=True, choices=[('<1', 'Меньше 1 часа'), ('1-3', '1–3 часа'), ('3-5', '3–5 часов'), ('>5', 'Более 5 часов')], max_length=20),
        ),
    ]
