# Generated by Django 5.1.4 on 2026-03-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_userprofile_interest_math_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
