# Generated by Django 5.1.4 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interest_math',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Как вы оцениваете свой интерес к математике?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest_programming',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Как вы оцениваете свой интерес к программированию?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_difficulties',
            field=models.JSONField(blank=True, default=list, verbose_name='С какими трудностями вы сталкиваетесь при обучении?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivation',
            field=models.JSONField(blank=True, default=list, verbose_name='Что вас мотивирует изучать программирование и математику?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_learning_formats',
            field=models.JSONField(blank=True, default=list, verbose_name='Какие форматы обучения вам больше нравятся?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_learning_time',
            field=models.CharField(blank=True, choices=[('<1', 'Меньше 1 часа в неделю'), ('1-3', '1–3 часа в неделю'), ('3-5', '3–5 часов в неделю'), ('>5', 'Более 5 часов в неделю')], max_length=20, verbose_name='Сколько времени вы обычно посвящаете обучению в неделю?'),
        ),
    ]
