# Generated by Django 5.1.4 on 2026-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('none', 'Не являюсь студентом'), ('cs101', 'CS-101'), ('cs102', 'CS-102'), ('math201', 'MATH-201')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dean', 'Деканат факультета'), ('headman', 'Староста группы'), ('student', 'Студент'), ('guest', 'Не являюсь студентом')], default='student', max_length=20),
        ),
    ]
