# Generated by Django 5.1.4 on 2026-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_customuser_group_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('non', 'Не являюсь студентом'), ('cs101', 'CS-101'), ('cs102', 'CS-102'), ('math201', 'MATH-201')], default='non', max_length=20),
        ),
    ]
