# Generated by Django 5.1.4 on 2026-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
