# Generated by Django 3.2.25 on 2026-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_customuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('non', 'Не являюсь студентом'), ('pmi51', 'ПМИ-51'), ('pmi52', 'ПМИ-52'), ('pmi53', 'ПМИ-53')], default='non', max_length=20),
        ),
    ]
